#!/bin/bash
#SBATCH -A mkmesmc
#SBATCH --job-name=S3_purge_haplotigs
#SBATCH -p bigmem
#SBATCH --ntasks=44
#SBATCH --mail-user=d.cowan-turner@newcastle.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --error=/nobackup/b3064455/job_output/kblossV5/S3_purge_haplotigs.err
#SBATCH --output=/nobackup/b3064455/job_output/kblossV5/S3_purge_haplotigs.out

#CoreSettings
CoreDir="/nobackup/proj/mkmesmc/KblossV5"
GenomeName="KblossV5"
DNAShortReads_1="/nobackup/proj/mkmesmc/Kbloss/ShortReads/AllReads/raw_short_merged_1.fq"
DNAShortReads_2="/nobackup/proj/mkmesmc/Kbloss/ShortReads/AllReads/raw_short_merged_2.fq"
LongReads="/nobackup/proj/mkmesmc/Kbloss2022/Reads/Nanopore/MergedLongReads.fq"
mascuradir=$CoreDir/S1_mascura
ragtag_dir=$CoreDir/S2_ragtag
purge_haplotigs_dir=$CoreDir/S3_purge_haplotigs
Genome_S2=$ragtag_dir/klax_cor_scaf/Kb.s2.fa

#File Prep
cd $CoreDir;mkdir $purge_haplotigs_dir;cd $purge_haplotigs_dir

#purge_haplotigs
module purge
source activate purge_haplotigs_env

minimap2 -t 44 -ax sr "$Genome_S2" "$DNAShortReads_1" "$DNAShortReads_2"\
--secondary=no  | samtools sort -m 500G -o aligned.bam -T tmp.ali

purge_haplotigs hist -b aligned.bam -g "$Genome_S2" -t 16
purge_haplotigs cov -i aligned.bam.gencov -l 10 -m 62 -h 190
purge_haplotigs purge -g "$Genome_S2" -c coverage_stats.csv


Genome_S3=$purge_haplotigs_dir/curated.fasta
module purge
#TheJollyLog
echo "S3_purge_haplotigs done"
echo "S3_purge_haplotigs done" >> $CoreDir/TheJolly.Log
